### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by balping** [rtctunnel/rtctunnel#25]
I get this error after about half a minute when running `rtctunnel run` (same happens on both client and sever side):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x78090c]

goroutine 1 [running]:
github.com/rtctunnel/rtctunnel/channels/apprtc.(*apprtcChannel).getConnection(0xedac70, 0xc0003034a0, 0x59, 0xa451c4, 0x4, 0x44885e, 0xc00037e000, 0xc00037c000)
	/home/user/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/channels/apprtc/apprtc.go:77 +0x17c
github.com/rtctunnel/rtctunnel/channels/apprtc.(*apprtcChannel).Send(0xedac70, 0xc0003034a0, 0x59, 0xc00037e000, 0xead, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/channels/apprtc/apprtc.go:53 +0x7a
github.com/rtctunnel/rtctunnel/signal.Send(0x74e0cfa327685aae, 0xc0201dbf2f0cad5f, 0x2d1420305558d136, 0x28debf1125c5b092, 0x2a58c441c272616f, 0x83a16947d456d379, 0x717c7e233b391e71, 0x520c55cdc2f871d4, 0x6ee9ccc043540cb9, 0xe14391f795dce849, ...)
	/home/user/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/signal/signal.go:61 +0x294
github.com/rtctunnel/rtctunnel/peer.sendSignal(0x74e0cfa327685aae, 0xc0201dbf2f0cad5f, 0x2d1420305558d136, 0x28debf1125c5b092, 0x2a58c441c272616f, 0x83a16947d456d379, 0x717c7e233b391e71, 0x520c55cdc2f871d4, 0x6ee9ccc043540cb9, 0xe14391f795dce849, ...)
	/home/user/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/peer/conn.go:270 +0xfc
github.com/rtctunnel/rtctunnel/peer.Open(0x74e0cfa327685aae, 0xc0201dbf2f0cad5f, 0x2d1420305558d136, 0x28debf1125c5b092, 0x2a58c441c272616f, 0x83a16947d456d379, 0x717c7e233b391e71, 0x520c55cdc2f871d4, 0x6ee9ccc043540cb9, 0xe14391f795dce849, ...)
	/home/user/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/peer/conn.go:171 +0x9cc
main.init.4.func1(0xc00016d900, 0xedac70, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/cmd/rtctunnel/cmd_run.go:61 +0x59b
github.com/spf13/cobra.(*Command).execute(0xc00016d900, 0xedac70, 0x0, 0x0, 0xc00016d900, 0xedac70)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xeb7d40, 0x0, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/user/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/cmd/rtctunnel/main.go:8 +0x31
```

**Comment by calebdoxsey** [comment]
Hi @balping . I was way behind on dependency updates so I turned dependabot on. I went ahead and released 0.7.0 which I think may fix this panic.

I was using Google's apprtc signaling server for a bit, but they changed everything and it no longer works (this is my fault not theirs... its not an API intended for public consumption) A custom signaling server is now the default.
